spring.application.name=ProcessarPagamentoService

pedidos.queue.name=pedidos-processar-pagamento-queue
pedidos.exchange.name=pedidos-exchange

spring.rabbitmq.username=myuser
spring.rabbitmq.password=secret
